name: Linting for accessibility issues

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dequelabs/axe-linter-action@v1
        with:
          api_key: 1da679cf-81cc-4137-b123-c420a077b8a5
          github_token: ${{ secrets.GITHUB_TOKEN }}
